# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paco < Formula
  desc "TUI package.json script runner"
  homepage "https://github.com/vianch/paco"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vianch/paco/releases/download/v0.2.0/paco_0.2.0_darwin_amd64.tar.gz"
      sha256 "9d0de77e70a99b5ba1becf9053087b56364805a37fa0c6655a0863d711b50fb7"

      define_method(:install) do
        bin.install "paco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vianch/paco/releases/download/v0.2.0/paco_0.2.0_darwin_arm64.tar.gz"
      sha256 "75445eeceb1352b595cf0910f09c157c52613350f32dd60b107727258ab157f4"

      define_method(:install) do
        bin.install "paco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vianch/paco/releases/download/v0.2.0/paco_0.2.0_linux_amd64.tar.gz"
      sha256 "156976fad2b5769aa85dc1ae377dc3490311b8f52f58f743d9a405942d961337"
      define_method(:install) do
        bin.install "paco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vianch/paco/releases/download/v0.2.0/paco_0.2.0_linux_arm64.tar.gz"
      sha256 "b65a7df22fdd515051d0137812cea4edc9a2b4005a35a4e0943c9fb81ca66d2c"
      define_method(:install) do
        bin.install "paco"
      end
    end
  end
end
