# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paco < Formula
  desc "TUI package.json script runner"
  homepage "https://github.com/vianch/paco"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vianch/paco/releases/download/v0.4.0/paco_0.4.0_darwin_amd64.tar.gz"
      sha256 "69f16df070b311e67d3014126fa1ed8a11b207fb083bd4642e46aac549757e71"

      define_method(:install) do
        bin.install "paco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vianch/paco/releases/download/v0.4.0/paco_0.4.0_darwin_arm64.tar.gz"
      sha256 "a6b1fcdfc957950a7c80ccd83fd3b27a172811fe15a43107d9b4b3de86ce11e1"

      define_method(:install) do
        bin.install "paco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vianch/paco/releases/download/v0.4.0/paco_0.4.0_linux_amd64.tar.gz"
      sha256 "5f8940174e0a29aef8caaa56fc8966bccb0cf853a60e438e93db9ce8853b3748"
      define_method(:install) do
        bin.install "paco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vianch/paco/releases/download/v0.4.0/paco_0.4.0_linux_arm64.tar.gz"
      sha256 "3b0f3e4ffb2abba97d7f04ee9e5db3f316bb2291a6508718f642d1637c27c76f"
      define_method(:install) do
        bin.install "paco"
      end
    end
  end
end
